"""
Taste profile service.

Deliberately NOT an LLM call — this is a fixed, small quiz, and a templated
summary is faster, free, and fully predictable. Save the LLM budget for
features that actually need judgment (concierge, verification).
"""

from app.models.taste_profile import DescriptiveWord, StyleCardItem, TasteProfileRequest

_LINE_WEIGHT_PHRASES = {"fine": "fine linework", "bold": "bold, graphic lines"}
_COLOR_PHRASES = {"color": "full color", "black_grey": "black and grey"}
_COMPOSITION_PHRASES = {"symmetrical": "symmetrical, structured composition", "organic": "organic, flowing composition"}


_DEFAULT_STYLE_DECK: list[StyleCardItem] = [
    # --- MINIMAL (1 - 9) ---
    StyleCardItem(
        id="minimal-botanical-1",
        title="Minimalist Wildflower Sprig",
        image_url="https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="minimal-line-profile-2",
        title="Single-Line Face Silhouette",
        image_url="https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="minimal-crescent-3",
        title="Micro Fine-Line Moon & Stars",
        image_url="https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="minimal-constellation-4",
        title="Minimal Constellation Map",
        image_url="https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="minimal-origami-5",
        title="Fine-Line Origami Crane",
        image_url="https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="minimal-wave-6",
        title="Japanese Minimalist Wave",
        image_url="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="minimal-lavender-7",
        title="Delicate Lavender Sprig",
        image_url="https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="minimal-geometric-8",
        title="Micro Triangle Coordinates",
        image_url="https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="minimal-script-9",
        title="Single-Needle Script",
        image_url="https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.minimal,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),

    # --- TRADITIONAL (10 - 18) ---
    StyleCardItem(
        id="traditional-swallow-10",
        title="Sailor Jerry Swallow",
        image_url="https://images.unsplash.com/photo-1562962230-16e4623d36e6?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="color",
        composition="organic",
    ),
    StyleCardItem(
        id="traditional-panther-11",
        title="Classic Crawling Panther",
        image_url="https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="traditional-dagger-12",
        title="Rose & Dagger Flash",
        image_url="https://images.unsplash.com/photo-1542385151-efd9000785a0?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="color",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="traditional-heart-13",
        title="Sacred Heart with Banner",
        image_url="https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="color",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="traditional-ship-14",
        title="Full-Rigged Clipper Ship",
        image_url="https://images.unsplash.com/photo-1519764622345-23439dd774f7?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="color",
        composition="organic",
    ),
    StyleCardItem(
        id="traditional-tiger-15",
        title="Traditional Tiger Roar",
        image_url="https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="color",
        composition="organic",
    ),
    StyleCardItem(
        id="traditional-eagle-16",
        title="Soaring Americana Eagle",
        image_url="https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="color",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="traditional-hannya-17",
        title="Japanese Hannya Mask",
        image_url="https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="color",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="traditional-snake-18",
        title="Coiled Viper & Peony",
        image_url="https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.traditional,
        line_weight="bold",
        color_approach="color",
        composition="organic",
    ),

    # --- GEOMETRIC (19 - 26) ---
    StyleCardItem(
        id="geometric-mandala-19",
        title="Sacred Geometry Lotus",
        image_url="https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.geometric,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="geometric-metatron-20",
        title="Metatron's Cube Dotwork",
        image_url="https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.geometric,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="geometric-polyhedron-21",
        title="Floating Polyhedron Orbit",
        image_url="https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.geometric,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="geometric-tessellation-22",
        title="Hexagon Optical Tessellation",
        image_url="https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.geometric,
        line_weight="bold",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="geometric-sleeve-23",
        title="Ornamental Dotwork Sleeve",
        image_url="https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.geometric,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="geometric-ouroboros-24",
        title="Geometric Ouroboros Circle",
        image_url="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.geometric,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="geometric-tree-25",
        title="Tree of Life Matrix",
        image_url="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.geometric,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="geometric-crystal-26",
        title="Prismatic Crystal Formation",
        image_url="https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.geometric,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),

    # --- ILLUSTRATIVE (27 - 34) ---
    StyleCardItem(
        id="illustrative-flora-27",
        title="Peonies & Wild Ferns",
        image_url="https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.illustrative,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="illustrative-serpent-28",
        title="Celestial Moon & Serpent",
        image_url="https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.illustrative,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="illustrative-moth-29",
        title="Death's-Head Hawkmoth",
        image_url="https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.illustrative,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="illustrative-wolf-30",
        title="Etched Timber Wolf",
        image_url="https://images.unsplash.com/photo-1528892952291-009c663ce843?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.illustrative,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="illustrative-tarot-31",
        title="Medieval Woodcut Sun Tarot",
        image_url="https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.illustrative,
        line_weight="bold",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="illustrative-raven-32",
        title="Dark Illustrative Raven",
        image_url="https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.illustrative,
        line_weight="bold",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="illustrative-whale-33",
        title="Cosmic Whale & Stars",
        image_url="https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.illustrative,
        line_weight="fine",
        color_approach="color",
        composition="organic",
    ),
    StyleCardItem(
        id="illustrative-heart-34",
        title="Anatomical Heart & Florals",
        image_url="https://images.unsplash.com/photo-1519764622345-23439dd774f7?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.illustrative,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),

    # --- BOLD / HEAVY BLACKWORK (35 - 42) ---
    StyleCardItem(
        id="bold-chevron-35",
        title="Tribal Chevron Armband",
        image_url="https://images.unsplash.com/photo-1568515045052-f9a854d70bfd?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.bold,
        line_weight="bold",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="bold-brutalist-36",
        title="Brutalist Heavy Blackwork",
        image_url="https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.bold,
        line_weight="bold",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="bold-polynesian-37",
        title="Polynesian Ornamental Cuff",
        image_url="https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.bold,
        line_weight="bold",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="bold-runic-38",
        title="Norse Vegvisir Runic Compass",
        image_url="https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.bold,
        line_weight="bold",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="bold-gothic-39",
        title="High-Contrast Gothic Cross",
        image_url="https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.bold,
        line_weight="bold",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="bold-cybersigil-40",
        title="Sharp Cybersigilism Blade",
        image_url="https://images.unsplash.com/photo-1611501275019-9b5cda994e8d?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.bold,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="bold-blackout-41",
        title="Solid Blackout Silhouette",
        image_url="https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.bold,
        line_weight="bold",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="bold-spine-42",
        title="Modern Flowing Spine Blackwork",
        image_url="https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.bold,
        line_weight="bold",
        color_approach="black_grey",
        composition="symmetrical",
    ),

    # --- DETAILED / MICROREALISM (43 - 50) ---
    StyleCardItem(
        id="detailed-sculpture-43",
        title="Renaissance Marble Sculpture",
        image_url="https://images.unsplash.com/photo-1590246814883-578337424689?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.detailed,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="detailed-lion-44",
        title="Hyper-Detailed Lion Head",
        image_url="https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.detailed,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="detailed-clockwork-45",
        title="Filigree Clockwork & Gears",
        image_url="https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.detailed,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="detailed-cathedral-46",
        title="Gothic Cathedral Arches",
        image_url="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.detailed,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="detailed-butterfly-47",
        title="Realistic Watercolor Monarch",
        image_url="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.detailed,
        line_weight="fine",
        color_approach="color",
        composition="organic",
    ),
    StyleCardItem(
        id="detailed-waves-48",
        title="Realistic Ocean Waves Portal",
        image_url="https://images.unsplash.com/photo-1543610892-0b1f7e6d8ac1?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.detailed,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
    StyleCardItem(
        id="detailed-medusa-49",
        title="Medusa Coiling Vipers",
        image_url="https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.detailed,
        line_weight="fine",
        color_approach="black_grey",
        composition="organic",
    ),
    StyleCardItem(
        id="detailed-astrolabe-50",
        title="Vintage Nautical Astrolabe",
        image_url="https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=900&q=80",
        word=DescriptiveWord.detailed,
        line_weight="fine",
        color_approach="black_grey",
        composition="symmetrical",
    ),
]


def get_default_style_deck(limit: int = 50) -> list[StyleCardItem]:
    return _DEFAULT_STYLE_DECK[:limit]


def build_summary(req: TasteProfileRequest) -> str:
    words = ", ".join(w.value for w in req.descriptive_words)
    line = _LINE_WEIGHT_PHRASES[req.line_weight]
    color = _COLOR_PHRASES[req.color_approach]
    composition = _COMPOSITION_PHRASES[req.composition]
    return (
        f"Drawn to {words} work, leaning toward {line} in {color}, "
        f"with a {composition}."
    )

